const fs = require("node:fs");
const path = require("node:path");
const { spawn } = require("node:child_process");

const ROUTES_DIR = path.join(__dirname, "..", "src", "routes");
const ENTRY_FILE = path.join(__dirname, "..", ".rainjs", "entry.ts");

const HTTP_METHODS = ["GET", "POST", "PUT", "DELETE"];

// -------------------------------------------------------
// src/routes/ を再帰的に走査して .ts ファイル一覧を返す
// -------------------------------------------------------
function getRouteFiles(dir, base = "") {
  if (!fs.existsSync(dir)) return [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relativePath = path.join(base, entry.name);

    if (entry.isDirectory()) {
      files.push(...getRouteFiles(fullPath, relativePath));
    } else if (entry.name === "index.ts" || /^\[.+\]\.ts$/.test(entry.name)) {
      files.push(relativePath);
    }
  }

  return files;
}

// -------------------------------------------------------
// ファイルパス → URL パス
//   routes/index.ts        → /
//   routes/user/index.ts   → /user
//   routes/user/[id].ts    → /user/:id
// -------------------------------------------------------
function filePathToUrlPath(filePath) {
  let urlPath = filePath.replace(/\.ts$/, "");
  urlPath = urlPath.replace(/\\/g, "/"); // Windows対応
  urlPath = urlPath.replace(/\[([^\]]+)\]/g, ":$1"); // [id] → :id
  urlPath = urlPath.replace(/\/index$/, ""); // /index → /
  if (urlPath === "index") urlPath = "";
  return `/${urlPath}`;
}

// -------------------------------------------------------
// ファイルパス → import 用の変数名
//   routes/user/[id].ts → route_user_$id
// -------------------------------------------------------
function filePathToImportName(filePath) {
  return (
    "route_" +
    filePath
      .replace(/\.ts$/, "")
      .replace(/\\/g, "_")
      .replace(/\//g, "_")
      .replace(/\[/g, "$")
      .replace(/\]/g, "")
      .replace(/-/g, "_")
  );
}

// -------------------------------------------------------
// ファイル内容から export されている HTTP メソッドを検出
// -------------------------------------------------------
function detectExportedMethods(filePath) {
  const content = fs.readFileSync(filePath, "utf-8");
  const found = [];
  for (const method of HTTP_METHODS) {
    // "export const GET" / "export function GET" / "export async function GET" にマッチ
    const pattern = new RegExp(
      `export\\s+(?:const|function|async\\s+function)\\s+${method}\\b`,
    );
    if (pattern.test(content)) {
      found.push(method);
    }
  }
  return found;
}

// -------------------------------------------------------
// ルート一覧からエントリファイル .rainjs/entry.ts を生成
// -------------------------------------------------------
function generate() {
  const dir = path.dirname(ENTRY_FILE);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const files = getRouteFiles(ROUTES_DIR);
  const imports = [];
  const registrations = [];

  for (const file of files) {
    const importName = filePathToImportName(file);
    const urlPath = filePathToUrlPath(file);
    const importPath = `../src/routes/${file.replace(/\.ts$/, "").replace(/\\/g, "/")}`;
    const fullPath = path.join(ROUTES_DIR, file);

    const methods = detectExportedMethods(fullPath);
    if (methods.length === 0) continue;

    // エイリアス付き named import で名前衝突を回避
    const importSpecifiers = methods
      .map((m) => `${m} as ${importName}_${m}`)
      .join(", ");
    imports.push(`import { ${importSpecifiers} } from "${importPath}";`);

    for (const method of methods) {
      const methodLower = method.toLowerCase();
      registrations.push(
        `app.${methodLower}("${urlPath}", ${importName}_${method});`,
      );
    }
  }

  const content = [
    "// AUTO-GENERATED FILE — DO NOT EDIT",
    "// This file is generated by scripts/dev.js from src/routes/",
    "",
    'import { Rain } from "../src/framework";',
    ...imports,
    "",
    "const app = new Rain();",
    "",
    ...registrations,
    "",
    "export default app;",
    "",
  ].join("\n");

  fs.writeFileSync(ENTRY_FILE, content);
  console.log(`[gen] ${files.length} route(s) → .rainjs/entry.ts`);
}

// -------------------------------------------------------
// メイン: 生成 → ファイル監視 → wrangler dev 起動
// -------------------------------------------------------

// 1. 初回生成
generate();

// 2. src/routes/ を監視して変更があれば再生成
let debounceTimer = null;
fs.watch(ROUTES_DIR, { recursive: true }, (eventType, filename) => {
  if (!filename?.endsWith(".ts")) return;
  // debounce: 短時間の連続変更をまとめる
  clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => {
    console.log(`[watch] ${eventType}: ${filename}`);
    generate();
  }, 100);
});
console.log("[watch] Watching src/routes/ for changes...");

// 3. wrangler dev を子プロセスとして起動
const wrangler = spawn("npx", ["wrangler", "dev"], {
  stdio: "inherit",
  shell: true,
  cwd: path.join(__dirname, ".."),
});

// Ctrl+C でプロセスを終了
process.on("SIGINT", () => {
  wrangler.kill();
  process.exit(0);
});

wrangler.on("close", (code) => {
  process.exit(code ?? 0);
});
